### ISSUE TITLE
Bad chip info at ATTiny9

### ISSUE THREAD

**Issue by hrzinap** [ZakKemble/AVRDUDESS#100]
![Snímek obrazovky (1749)](https://github.com/user-attachments/assets/6a1a2ea7-a26b-462b-a51c-416f07a256ef)

Hi,
i report this error:
The GUI generate for CPU ATTiny9  this string: " -c usbasp -p t9"
This is O.k. but to AVRDUDE send another one:  avrdude.exe -c usbasp -p m8 

Thank you, for fix.  Pavel.

**Comment by ZakKemble** [comment]
Heya, this is a known problem - https://github.com/ZakKemble/AVRDUDESS/issues/26
