### ISSUE TITLE
Remove Mono icon from docky  and leave only an icon for AVRDUDDESS in Ubuntu

### ISSUE THREAD

**Issue by FernandoGarcia** [ZakKemble/AVRDUDESS#23]
In case someone is interested here the script that I did to remove Mono icon from docky.

```
#!/bin/bash
for ((var = 0; var < 5; var++)); do
    if((var == 0)); then
        nohup mono avrdudess.exe --runtime=4 > program.out &
    fi
    sleep 1
    xprop -name "AVRDUDESS 2.8 (avrdude version 6.3)" -f WM_CLASS 8s -set WM_CLASS "avrdudessicone"
done
```

Add `StartupWMClass=avrdudessicone` to .desktop file.

Adjust window title `AVRDUDESS 2.8 (avrdude version 6.3)` if needed.

I'm using [binaries](http://blog.zakkemble.net/download/avrdudess_20190209.zip) since `setup-AVRDUDESS-2.8.exe`  doesn't not work for me.

![avrdudess](https://user-images.githubusercontent.com/2778501/63778260-dab0c180-c8ba-11e9-83f0-4fc653c15ec2.png)

@zkemble can you add a `StartupWMClass` to your script please?

**Comment by zkemble** [comment]
Nice, could be useful!

> I'm using binaries since setup-AVRDUDESS-2.8.exe doesn't not work for me.
setup-AVRDUDESS-2.8.exe is only for Windows

>@zkemble can you add a StartupWMClass to your script please?
I'm not sure what you mean by that, there aren't any scripts that this might go in.
