### ISSUE TITLE
"Fuse && lock bits: Atmea32u4" window - Warning: Unsuported MCU

### ISSUE THREAD

**Issue by Ser9ei** [ZakKemble/AVRDUDESS#44]
Add support (or correct warning notification) of the Atmea32u4 MCU in the "Fuse && lock bits" window.
Please see screenshot in the attach.

![message](https://user-images.githubusercontent.com/61657001/113330636-049c5680-9330-11eb-80c2-2c93b2de5d6f.JPG)

**Comment by Ser9ei** [comment]
I believe the "bits.xml" file should be update by text below:

	<mcu signature="1e9587" name="atmega32u4">
		<high>BOOTRST,BOOTSZ0,BOOTSZ1,EESAVE,WDTON,SPIEN,JTAGEN,OCDEN</high>
		<low>CKSEL0,CKSEL1,CKSEL2,CKSEL3,SUT0,SUT1,CKOUT,CKDIV8</low>
		<ext>BODLEVEL0,BODLEVEL1,BODLEVEL2,HWBE,,,,</ext>
		<lock>LB1,LB2,BLB01,BLB02,BLB11,BLB12,,</lock>

**Comment by zkemble** [comment]
Alright, I'll add those fuse bit settings for the next release. You can submit a pull request instead if you want to.
