### ISSUE TITLE
Attiny10 and tpi interface support in the AVRDUDESS

### ISSUE THREAD

**Issue by Ser9ei** [ZakKemble/AVRDUDESS#46]
Attiny10 has only tpi interface for programming. Some features in the AVRDUDESS has limited support for the attiny10 chip.

(1) Function of chip's detection doesn't work with attiny tpi interface.
for example, attiny10 cannot be detected, because command line for spi interface doesn't work with chip with tpi interface, see sample below:
>>>: avrdude -u -c usbasp -P usb -B 8.0 -q  -C avrdude.conf -p m8 

Command line below works correctly for chip with the tpi interface  :
>>>: avrdude -u -c usbasp -P usb -B 8.0 -q  -C avrdude.conf -p t10 

(2) Also, please, add support attiny10 in the "Fuse && Lock bits" window
The sample is below:

	<mcu signature="1e9003" name="attiny10">
		<high>,,,,,,,</high>
		<low>CKOUT,WDTON,RSTDISBL,,,,,</low>
		<ext>,,,,,,,</ext>
		<lock>LB1,LB2,,,,,,</lock>

**Comment by zkemble** [comment]
(1) Known issue, see https://github.com/zkemble/AVRDUDESS/issues/26
(2) I'll get that added, you're welcome to submit a pull request too.
