### ISSUE TITLE
Does not support newer TinyAVR0, 1, 2 parts with Atmel-ICE in UPDI mode

### ISSUE THREAD

**Issue by EclipseBoom** [ZakKemble/AVRDUDESS#54]
Tested the GUI with ATtiny1626 connected to Atmel-ICE in UPDI mode.  AVRDudess displays the proper command string above the console area as the -p parameter says -p t1626 but when the command is issued to avrdude it actually sends -p m8

Using the very latest avrdude.conf and avrdude.exe copied from the megaTinyCore project.

Please add support for these newer ATTiny parts.  They are very cool and provide a lot of functions in a small low-cost package.  I prefer them to ATMega parts for small simple projects.

**Comment by zkemble** [comment]
See this https://github.com/zkemble/AVRDUDESS/issues/26
It's just auto-detect and fuses that doesn't work (only high, low and extended fuses are supported at the moment), everything else should be working fine.
