### ISSUE TITLE
Push flash in atemga16

### ISSUE THREAD

**Issue by nghiank97** [ZakKemble/AVRDUDESS#56]
I have a project in **atmega16**. I using **USP ISP** to push the hex file. But, I don't know how to setup. Please help me

![image](https://user-images.githubusercontent.com/42688892/134770081-f3449fd7-1dc0-43af-ab47-2d566a82f56a.png)
![av00700-01-thumbnail-1080x1080-70](https://user-images.githubusercontent.com/42688892/134770168-5d70bc8c-ed4a-4f2e-9cba-c5dd0078872e.jpg)

**Comment by DirtyEngineer** [comment]
You need to select the correct programmer.  In the top left drop-down select either "USBasp, http://www.fischl.de/usbasp/" or "Any usbasp clone with correct VID/PID". Next click the "Detect" button on the top right side. If you have made the correct connections the lower text box will show the signature/name of your chip. Then click the program button.

**Comment by nghiank97** [comment]
**Thank for your response**

I have try it, but i don't
When I select **"USBasp, http://www.fischl.de/usbasp/"** and press "Detect". The commend show **"could not find USB ...."**

![image](https://user-images.githubusercontent.com/42688892/134785290-b22bb20a-ca8d-414f-a985-0f3eb4363805.png)

This is the same when I select **"Any usbasp clone with correct VID/PID"**

But when i select **"Atmel AVR ISP"**

![image](https://user-images.githubusercontent.com/42688892/134785417-b23f8728-1fab-4cad-8bf0-41ca19ea3f4a.png)

**Comment by DirtyEngineer** [comment]
Does the programmer show up in your Device Manager? If not you probably need to download the drivers for it. Goggle should be able to help with how to get it to work.

**Comment by nghiank97** [comment]
ok, many thanks
