### ISSUE TITLE
AVRDUDE 6.4/7.0 \o.o/

### ISSUE THREAD

**Issue by ZakKemble** [ZakKemble/AVRDUDESS#60]
6.4 was released a few months ago ( http://download.savannah.gnu.org/releases/avrdude/ ), but it's missing libhidapi-0.dll.
The .dll can be downloaded here - https://github.com/libusb/hidapi/releases/tag/hidapi-0.11.2 then place the x86 version into the AVRDUDESS directory and rename it to libhidapi-0.dll

**Comment by zkemble** [comment]
Official avrdude repo: https://github.com/avrdudes/avrdude
Forked repo with v7.0-rc1: https://github.com/mariusgreuel/avrdude/releases/tag/v7.0-rc1

**Comment by DirtyEngineer** [comment]
Finally actual Atmel-ICE support! This is wonderful.

**Comment by ro-bercik** [comment]
Version 7.0RC1 tested with FT232R (programmer: arduino-ft232r), it works without any problems and without any external dlls.

**Comment by steigerbalett** [comment]
AVRDUDE Version: 7.0RC1
Tested with: USBasp
Works without any problems

**Comment by ZakKemble** [comment]
Official v7.0 released a few hours ago https://github.com/avrdudes/avrdude/releases/tag/v7.0

**Comment by pcfreak1201** [comment]
AVRDUDESS-2.14-portable and avrdude-7.0 (compiled) works on Linux Mint 20.3 Una (base: Ubuntu 20.04 focal), but needed to change to avrdude-7.0.conf for full support - great!
