### ISSUE TITLE
ATMEL ICE DRIVERS. Add to Readme.

### ISSUE THREAD

**Issue by jacky4566** [ZakKemble/AVRDUDESS#62]
More of an FYI. Maybe add this to the readme. For windows users with Atmel ICE.

Under AVRDUDE 6.3 I was forced to use these drivers:
**FOR AVR DUDE**
_CMSIS libusb0 1.2.6.0
DATA GATEWAY WinUSB 42.0.2.0 OR libusb 1.2.6.0_

**For Atmel Studio**	
_CMSIS HidUsb v6.1.7601 (Uninstall)
Gateway WinUSB 6.1.76_

Under AVRDUDE 6.4+ you can now use the same drivers for both. 
_CMSIS HidUsb v6.1.7601
Gateway WinUSB 6.1.76_

_Zadig is a great tool for swapping drivers._

**Comment by ZakKemble** [comment]
Closing for now. This probably happens with a lot of programmers and isn't really anything to do with AVRDUDESS.
