### ISSUE TITLE
Windows defender warns about virus in the AVRDUDESS-2.14-setup.exe file

### ISSUE THREAD

**Issue by Ser9ei** [ZakKemble/AVRDUDESS#63]
actions:
1. Try to download the AVRDUDESS-2.14-setup.exe file
2. After the downloaded is complete, the Defender warns about virus in the installation file
Please find details in the screenshot below.
![ar1](https://user-images.githubusercontent.com/61657001/168156091-2815b930-cbcc-4d5d-b003-4004d09589de.JPG)

Portable version (and AVRDUDESS-2.13-setup.exe file) doesn't have issue with Defender

**Comment by ZakKemble** [comment]
Antivirus programs have always hated AVRDUDESS or the installer for some reason :(
Odd that my Defender doesn't see it as a problem. I will see if I can submit a false positive report to Microsoft.

**Comment by ZakKemble** [comment]
Microsoft has removed the detection which should be included in the next definition update.

**Comment by Ser9ei** [comment]
Thanks, Zak, for the new release
