### ISSUE TITLE
Have some small problems

### ISSUE THREAD

**Issue by Manhem** [ZakKemble/AVRDUDESS#76]
Hi.
I found this software and I have tried it but I get some small problem.
So I hope someone can help me to get it to work.
I'm using a Arduino Uno as ISP connected to a Atmega328 over ISP that I like to program.
You can see my setting later.

If I press **Detect** I get this: _ERROR: Unknown signature 000000_
Also if I press **Program** I get this: 
_>>>: avrdude -C "C:\Program Files (x86)\Arduino\hardware\tools\avr\bin\avrdude.conf" -c arduino -p m328 -P COM46 -b 19200 -F -U flash:w:"Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex":a -U eeprom:w:"Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.eep":a 

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x000000
avrdude.exe: Yikes!  Invalid device signature.
avrdude.exe: Expected signature for ATmega328 is 1E 95 14
avrdude.exe: NOTE: "flash" memory has been specified, an erase cycle will be performed
             To disable this feature, specify the -D option.
avrdude.exe: erasing chip
avrdude.exe: reading input file "Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex"
avrdude.exe: input file Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex auto detected as Intel Hex
avrdude.exe: writing flash (26594 bytes):

Writing | ################################################## | 100% 29.33s

avrdude.exe: 26594 bytes of flash written
avrdude.exe: verifying flash memory against Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex:
avrdude.exe: load data flash data from input file Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex:
avrdude.exe: input file Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex auto detected as Intel Hex
avrdude.exe: input file Z:\Projekt\Solfångareprojekt Johannes\JSON_Fronius.hex contains 26594 bytes
avrdude.exe: reading on-chip flash data:

Reading | ################################################## | 100% 16.22s

avrdude.exe: verifying ...
avrdude.exe: verification error, first mismatch at byte 0x0000
             0x00 != 0x0c
avrdude.exe: verification error; content mismatch

avrdude.exe: safemode: Fuses OK (E:00, H:00, L:00)

avrdude.exe done.  Thank you._

Everything seems to work but I got some errors what ever I do.
And the programmed equipment haven't got the new software into it.

Do anyone no what I'm doing wrong and can help me?

![image](https://user-images.githubusercontent.com/76493147/235298251-50ae2326-c895-49fd-8939-eaeabceefd97.png)

**Comment by DirtyEngineer** [comment]
This isn't an issue with AVRDUDESS. There is an issue with your hardware, either your programmer or the chip your trying to program. Check that your Uno is programmed correctly, check your wiring and make sure the reset is wired to the right pins. Try a different chip. Use the "Detect" button to check that everything is working correctly. Don't use the "Force" check box.
