### ISSUE TITLE
AVRDUDE 7.2 - new format of avrdude.conf

### ISSUE THREAD

**Issue by ro-bercik** [ZakKemble/AVRDUDESS#78]
There is a new version of avrdude.exe from official repo: https://github.com/avrdudes/avrdude
But... there was some changes in avrdude.conf config file.
The "id" tag in "programmer" section now contains multiply strings, so code for AvrDudess need some updates.

Here is an example:
v7.1) avrdude.conf:
programmer
    id                     = "arduino-ft232r";
    desc                   = "Arduino: FT232R connected to ISP";
    type                   = "ftdi_syncbb";

v7.2) avrdude.conf:
programmer
    id                     = "arduino-ft232r", "diecimila";
    desc                   = "Arduino: FT232R connected to ISP";
    type                   = "ftdi_syncbb";

Actual version of AvrDudess detects programmer as: "-c arduino-ft232r", "diecimila". Now it should be divided in two different standard commands: "-c arduino-ft232r" and "-c diecimila".
![avrdudess 7 2](https://github.com/ZakKemble/AVRDUDESS/assets/43404500/542b1795-98f9-4434-b326-62e6b0f0e59c)

**Comment by BlackBrix** [comment]
I second that
+1

**Comment by ZakKemble** [comment]
Fixed in this commit https://github.com/ZakKemble/AVRDUDESS/commit/905a19d74852085cc2e04a9077b8ec265b69d51c and now available in v2.15 - https://github.com/ZakKemble/AVRDUDESS/releases/tag/v2.15
