### ISSUE TITLE
Unable to detect Atmel-ICE in ISP Mode. Right drivers installed

### ISSUE THREAD

**Issue by dzalf** [ZakKemble/AVRDUDESS#82]
For the life of me, I cannot get AVRDUDESS to detect and work with ATMEL-ICE programmer.

<img width="486" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/27e6e919-f424-4ab0-96ae-eeb0c88efb89">

I correctly installed the libusb32 drivers using the Zadig tool.

Interestingly, I am able to program the bootloader and code using platformio.

What is happening?

<img width="501" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/577a60e3-fd37-4410-9eac-e6e67e63d7d9">

**Comment by ZakKemble** [comment]
Heya, try deleting the contents in the Port (-P) box, so it's just blank.

**Comment by dzalf** [comment]
Hi @ZakKemble 

Thanks for your prompt response.

Unfortunately, it didn't work. Still unable to communicate with the programmer

<img width="480" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/b92d3698-35f6-4f8b-896b-616b425b2c0e">

I still don't get it. The hardware VID and PID are correct to me:

<img width="304" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/36fa401e-e425-40fd-9aca-0f9354bcd8a1">

**Comment by ZakKemble** [comment]
Are you able to get the command line args that works with platformIO? What version of avrdude are they using? I think this might be more of an issue with avrdude rather than this GUI. https://github.com/avrdudes/avrdude

**Comment by dzalf** [comment]
Well, this is getting weird.

Could it be related to different versions being used by the pio environment and the avrdudess GUI?

I located the `tool-avrdude` folder from platformio and ran the same command as in the GUI consode and got what I expected:

**Comment by dzalf** [comment]
Yep! My suspicions were right. I believe that there is an issue with the avrdude executable packed with the latest version of this GUI.

I pointed at the executable from the platformio folder and I was able to detect the MCU!

<img width="483" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/dbe6f65f-9035-4af9-a72e-f42ffe2d492f">

<img width="401" alt="image" src="https://github.com/ZakKemble/AVRDUDESS/assets/3759916/30c3cc22-086f-4653-8819-5b23bf962146">

**Comment by ZakKemble** [comment]
Yea, I would raise this at https://github.com/avrdudes/avrdude since there's nothing I can do here.

**Comment by dzalf** [comment]
Got it. Thank you for your support, though.

Best wishes and thank you for the amazing work with avrdudess!

**Comment by dzalf** [comment]
Just one last question. Is the AVRDUDESS GUI always compiled from the latest avrdude branch? In other words, you have nothing to do with the executable packed with the GUI, correct?

**Comment by ZakKemble** [comment]
Correct, I have nothing to do with avrdude. I just ship the GUI with whatever the latest version of avrdude is at the time.

**Comment by ZakKemble** [comment]
Oh I just remembered this issue #62 which might have some clues.

**Comment by dzalf** [comment]
> Oh I just remembered this issue #62 which might have some clues.

I did check that issue before, however, I tried with multiple drivers with no luck 😕

**Comment by mcuee** [comment]
@dzalf 

You should not use libusb-win32 device driver for Atmel-ICE. You should use native Windows USB HID device driver.
