### ISSUE TITLE
Latests Polish file

### ISSUE THREAD

**Issue by ro-bercik** [ZakKemble/AVRDUDESS#86]
Hi,
here is latest file for Polish language, stage at commit #211d498.
[polish.txt](https://github.com/ZakKemble/AVRDUDESS/files/13997285/polish.txt)

**Comment by ZakKemble** [comment]
Awesome! `AVRDUDE_LOCATION`, `AVRDUDECONF_LOCATION` and `AVRSIZE_LOCATION` have also been updated, they no longer have the word "folder"

**Comment by ro-bercik** [comment]
Ok, I get this.
[polish.txt](https://github.com/ZakKemble/AVRDUDESS/files/13999602/polish.txt)
