### ISSUE TITLE
Error code after install avrdudess 2.17

### ISSUE THREAD

**Issue by rudolf58** [ZakKemble/AVRDUDESS#94]
Hello.
I got an error after installing avrdudess like that:

FEHLER: avrdude fehlt!
FEHLER: avrdude.con fehlt !
End Message
....... but both files exists in the folder !

System: Win10 64, the bug must be in the environmet of the system, because in a second System 
on that machine AVRDUDESS works fine.

I have no idea how to fix that bug, may be it is a missing item in the registry or something like that.

I didn't use avrdudess for a longer time, in the meantime I installed some other programs, may be that this is the reason .....
This programs are for example fusion360, estlacm, bambulab, eagle, Arduino in two Versions and some other programs.

I installed Win10 again without progress.

Would be fine to show me a way to how fix that problem.

**Comment by ZakKemble** [comment]
Hi, in Options, make sure the fields for avrdude and avrdude.conf are blank to enable autodetection. They've recently changed so that they should point directly to the .exe and .conf instead of just the folder.

**Comment by rudolf58** [comment]
Thanks a lot ! 
Now it works fine.
I like this tool so much !
