### ISSUE TITLE
Avrdudess wrong device (-p) selected for ATmega4808

### ISSUE THREAD

**Issue by oldbrad** [ZakKemble/AVRDUDESS#95]
'ATmega4808' is selected in avrdudess. When 'Detect' clickred status displayed is:
>>>: avrdude -C "/usr/local/etc/avrdude.conf" -c serialupdi -P /dev/ttyUSB0 -b 19200 -p m8 <<<<< WRONG

Entering the correct device m4808 in an avrdude command line:
$ avrdude -C "/usr/local/etc/avrdude.conf" -c serialupdi -P /dev/ttyUSB0 -b 19200 -p m4808
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9650 (probably m4808)

**Comment by ZakKemble** [comment]
Heya, this is a known problem with auto-detect - see #26
